# Generated by Django 2.0.13 on 2019-02-18 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='remark',
            field=models.TextField(default='New'),
            preserve_default=False,
        ),
    ]
